name: タスク
description: リファクタリング、ドキュメント、その他のタスク
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        機能追加でもバグ修正でもないタスク(リファクタリング、ドキュメント更新、設定変更など)用のIssueです。

  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: タスクの内容を簡潔に説明
      placeholder: "例: APIクライアントのリファクタリング"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 背景・動機
      description: なぜこのタスクが必要か
      placeholder: "例: コードの可読性を向上させたい"

  - type: textarea
    id: tasks
    attributes:
      label: タスク
      description: 細かいタスクに分解(チェックリスト形式推奨)
      placeholder: |
        - [ ] 型定義を整理
        - [ ] 関数を分割
        - [ ] テスト更新

  - type: dropdown
    id: type
    attributes:
      label: タイプ
      options:
        - refactor(リファクタリング)
        - docs(ドキュメント)
        - chore(設定・依存関係)
        - perf(パフォーマンス改善)
        - test(テスト追加)

  - type: dropdown
    id: area
    attributes:
      label: 影響範囲
      multiple: true
      options:
        - frontend
        - backend
        - packages/types
